### ISSUE TITLE
[System] Pre-populate docker volumes with config files

### ISSUE THREAD

**Issue by Falcon2k1** [phntxx/dashboard#15]
Using Docker image: phntxx/dashboard:latest, pulled today on an ubuntu server VM.

Hi! I just found this out and it's a pretty cool program, but I ran into some weird behavior that I suspect might be a bug, either with your docker configuration or something else.

For starters, I'm launching the docker container using the following, username swapped out:

```
version: "3"

services:
  dashboard:
    image: phntxx/dashboard:latest
    container_name: dashboard
    restart: unless-stopped
    volumes:
      - /home/<username>/docker_data/dashboard:/app/data
    ports:
      - 8080:8080
```

On first launch no files were populated, which was a little confusing but I just grabbed them from the repo and that worked out fine and it started to render. 

Not sure if this is intentional; if it is, you should include some additional documentation in the docker readme or here on the github. Other containers I've used tend to pre-populate data if it doesn't exist.

**However**, after that, there's a second strangeness that's more of a significant issue. 

In Chrome and Edge, the dashboard doesn't seem to be making links for any of the apps, just...lines. Viewing developer console shows that they look like : `<a class="sc-kstrdz btjemE">pfSense</a>` but aren't clickable or anything, leading to either example.com or a real one if filled out correctly. 

I reviewed the documentation and I don't see anything I'm missing that would lead to Dashboard just not rendering the links.
