### ISSUE TITLE
[Theme] Modify font and icon sizing

### ISSUE THREAD

**Issue by millerjs2** [phntxx/dashboard#19]
Hello!
I discovered your project this morning and instantly fell in love with it, this is exactly what I have been looking for for a while. I do have a couple of questions and a request.

1) Is it possible to set a favicon? This is mostly an aesthetic request, but it would be really nice.

2) Is it possible to make the font and icons a bit bigger? Is this controlled with a theme?

3) It would be really nice if the entire area for an entry could be clickable, rather than just the title. This would probably take the most effort to implement, but it would be really helpful from an ease-of-use perspective.

Thanks!
John

**Comment by phntxx** [comment]
Hi!

First of all I'd just like to say that comments like your initial one always humble me. Thank you very much for loving the stuff I write as much as you seem you do.

I'll just go through your points one-by-one to make sure I get everything covered:

> 1. Is it possible to set a favicon? This is mostly an aesthetic request, but it would be really nice.

It is actually, I just forgot to write documentation for it. If you look [here](https://github.com/phntxx/dashboard/blob/master/public/index.html), the code for it is there. I've personally used [this favicon generator](https://www.favicon-generator.org) and mounted the folder with all of the icons at `/app/icon`, making my docker-command look like this:

```yml
version: "3"

services:
  dashboard:
    image: phntxx/dashboard:latest
    restart: unless-stopped
    environment:
      - CLOUDFLARE_ZONE_ID=[OPTIONAL CLOUDFLARE V4 ZONE ID]
      - CLOUDFLARE_PURGE_TOKEN=[OPTIONAL CLOUDFLARE PURGE TOKEN]
    volumes:
      - [path to data directory]:/app/data
      - [path to favicon directory]:/app/icon
    ports:
      - 8080:8080
```

> 2. Is it possible to make the font and icons a bit bigger? Is this controlled with a theme?

While theoretically possible, it's not possible through any configs. All of these parameters are hardcoded. Good idea though.

> 3. It would be really nice if the entire area for an entry could be clickable, rather than just the title. This would probably take the most effort to implement, but it would be really helpful from an ease-of-use perspective.

This is actually one of the easier things to implement. It could definitely be done, I'll also note that idea.
