### ISSUE TITLE
Can't run on Raspberry Pi 4B w/ Ubuntu Server 64-bit

### ISSUE THREAD

**Issue by leonbeon** [phntxx/dashboard#49]
Hey, running this as a Docker container on a Raspberry Pi 4B with Ubuntu Server x64 outputs `standard_init_linux.go:228: exec user process caused: exec format error` to the logs. This seems to be a common error message for architecture mismatch. RPi4B runs on `aarch64`/`arm64/v8`. There seems to be no build for this arch for the `ratisbonacoding/nginx-cloudflare-cache` image this builds on (according to [DockerHub](https://hub.docker.com/r/ratisbonacoding/nginx-cloudflare-cache/tags)). The `nginxinc/nginx-unprivileged` image the cloudflare container is depending on has builds for armv8 ([DockerHub](https://hub.docker.com/r/nginxinc/nginx-unprivileged/tags)).  

Could there be a version which is just straight up depending on nginx-unpriviliged, skipping the cloudflare-cache container? Thanks!

**Comment by SkYNewZ** [comment]
This is mine :) running on k3s on Raspberrypi 4

```dockerfile
FROM phntxx/dashboard as builder
FROM nginxinc/nginx-unprivileged:alpine
COPY --from=builder /app /usr/share/nginx/html
```

With

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dashboard
    app.kubernetes.io/part-of: dashboard
  name: dashboard
  namespace: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dashboard
      app.kubernetes.io/part-of: dashboard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dashboard
        app.kubernetes.io/part-of: dashboard
    spec:
      containers:
      - image: rg.fr-par.scw.cloud/cc2b5a5b-09f9-4378-afd3-badc4b2865ac/phntxx/dashboard:latest
        name: dashboard
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html/data
          name: config
          readOnly: true
      restartPolicy: Always
      volumes:
      - configMap: # contains the JSON files, autogenerated with kustomize from a yaml file (more readable)
          name: config-562662tg42
        name: config
```
